import React, { useState } from 'react';
import { ArrowLeft, User as UserIcon, Shield, Check, Trash2, Ban } from 'lucide-react';
import { toast } from 'sonner';
import { User as UserType, UserRole } from '../../types';

interface AddStaffFormProps {
  onBack: () => void;
  onSave: (user: UserType & { password?: string }) => void;
  onDelete?: (userId: string) => void;
  editingUser?: UserType | null;
}

const ROLES: UserRole[] = ['Admin', 'Veterinarian', 'Lab Scientist', 'Lab Tech', 'Vet Tech', 'Vet Assistant', 'Receptionist'];

export const AddStaffForm: React.FC<AddStaffFormProps> = ({ onBack, onSave, onDelete, editingUser }) => {
  const [formData, setFormData] = useState<Partial<UserType>>({
    name: editingUser?.name || '',
    email: editingUser?.email || '',
    username: editingUser?.username || '',
    password: '',
    roles: editingUser?.roles || [],
    status: editingUser?.status || 'Active'
  });

  const handleRoleToggle = (role: UserRole) => {
    setFormData(prev => {
      const currentRoles = prev.roles || [];
      if (currentRoles.includes(role)) {
        return { ...prev, roles: currentRoles.filter(r => r !== role) };
      } else {
        return { ...prev, roles: [...currentRoles, role] };
      }
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name?.trim()) {
      toast.error('Full name is required');
      return;
    }
    if (!formData.email?.trim()) {
      toast.error('Email address is required');
      return;
    }
    if (!formData.username?.trim()) {
      toast.error('Username is required');
      return;
    }
    if (!formData.roles?.length) {
      toast.error('At least one role must be selected');
      return;
    }
    if (!editingUser && (!formData.password || formData.password.length < 6)) {
      toast.error('Password must be at least 6 characters');
      return;
    }

    const userToSave: UserType & { password?: string } = editingUser ?
      {
        ...editingUser,
        name: formData.name!,
        email: formData.email!,
        username: formData.username,
        roles: formData.roles!,
        status: formData.status!
      } :
      {
        id: '', // Will be generated by backend
        name: formData.name!,
        email: formData.email!,
        username: formData.username,
        password: formData.password || '123456',
        roles: formData.roles!,
        status: formData.status as 'Active' | 'Suspended',
        isSuperAdmin: false,
        clinicId: undefined
      };

    onSave(userToSave);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex items-center gap-4">
        <button
          onClick={onBack}
          className="p-2 hover:bg-slate-100 rounded-lg text-slate-500 transition"
        >
          <ArrowLeft className="w-5 h-5" />
        </button>
        <div>
          <h1 className="text-3xl font-extrabold text-slate-800 tracking-tight">
            {editingUser ? 'Edit Staff Member' : 'Add New Staff'}
          </h1>
          <p className="text-slate-400 font-medium text-sm">
            {editingUser ? 'Update staff member information and roles' : 'Create a new staff member account'}
          </p>
        </div>
      </div>

      <div className="max-w-2xl">
        <form onSubmit={handleSubmit} className="soft-card p-8">
          <div className="space-y-6">
            {/* Basic Information */}
            <div className="space-y-4">
              <h2 className="font-bold text-slate-700 flex items-center gap-2">
                <UserIcon className="w-5 h-5 text-amber-500" />
                Basic Information
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-xs font-bold text-slate-500 uppercase">Full Name</label>
                  <input
                    required
                    value={formData.name}
                    onChange={e => setFormData({ ...formData, name: e.target.value })}
                    className="w-full soft-input px-4 py-3 font-bold text-slate-700"
                    placeholder="Enter full name"
                  />
                </div>

                <div className="space-y-2">
                  <label className="text-xs font-bold text-slate-500 uppercase">Username <span className="text-[10px] text-slate-400 font-normal">(Optional)</span></label>
                  <input
                    value={formData.username}
                    onChange={e => setFormData({ ...formData, username: e.target.value })}
                    className="w-full soft-input px-4 py-3 font-bold text-slate-700"
                    placeholder="Enter username"
                  />
                  <p className="text-xs text-slate-400">Used for login and custom welcome messages</p>
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-xs font-bold text-slate-500 uppercase">Email Address</label>
                <input
                  required
                  type="email"
                  value={formData.email}
                  onChange={e => setFormData({ ...formData, email: e.target.value })}
                  className="w-full soft-input px-4 py-3 font-bold text-slate-700"
                  placeholder="Enter email address"
                />
              </div>

              {!editingUser && (
                <div className="space-y-2">
                  <label className="text-xs font-bold text-slate-500 uppercase">Password</label>
                  <input
                    type="password"
                    required
                    minLength={6}
                    value={formData.password}
                    onChange={e => setFormData({ ...formData, password: e.target.value })}
                    placeholder="Enter login password (min 6 characters)"
                    className="w-full soft-input px-4 py-3 font-bold text-slate-700"
                  />
                  <p className="text-xs text-slate-400">Password must be at least 6 characters</p>
                </div>
              )}
            </div>

            {/* Roles */}
            <div className="space-y-4">
              <h2 className="font-bold text-slate-700 flex items-center gap-2">
                <Shield className="w-5 h-5 text-amber-500" />
                Roles & Permissions
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {ROLES.map(role => (
                  <div
                    key={role}
                    onClick={() => handleRoleToggle(role)}
                    className={`cursor-pointer px-4 py-3 rounded-xl text-sm font-bold border-2 transition-all flex items-center gap-3
                      ${formData.roles?.includes(role)
                        ? 'border-amber-500 bg-amber-50 text-amber-700'
                        : 'border-slate-100 bg-slate-50 text-slate-400 hover:border-slate-200'
                      }
                    `}
                  >
                    {formData.roles?.includes(role) && <Check className="w-4 h-4" />}
                    <div>
                      <div>{role}</div>
                      <div className="text-xs font-normal opacity-75">
                        {role === 'Admin' && 'Full system access'}
                        {role === 'Veterinarian' && 'Medical treatments & prescriptions'}
                        {role === 'Lab Scientist' && 'Laboratory results & diagnostics'}
                        {role === 'Lab Tech' && 'Upload lab results & manage samples'}
                        {role === 'Vet Tech' && 'Assist with treatments & care'}
                        {role === 'Vet Assistant' && 'Basic patient care'}
                        {role === 'Receptionist' && 'Client management & billing'}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Status (for editing) */}
            {editingUser && (
              <div className="space-y-4">
                <h2 className="font-bold text-slate-700">Account Status</h2>
                <div className="flex gap-4">
                  <button
                    type="button"
                    onClick={() => setFormData({ ...formData, status: formData.status === 'Active' ? 'Suspended' : 'Active' })}
                    className={`flex-1 py-3 rounded-xl font-bold text-sm flex items-center justify-center gap-2 ${formData.status === 'Active'
                      ? 'bg-rose-50 text-rose-500 hover:bg-rose-100'
                      : 'bg-emerald-50 text-emerald-600 hover:bg-emerald-100'
                      }`}
                  >
                    <Ban className="w-4 h-4" />
                    {formData.status === 'Active' ? 'Suspend User' : 'Activate User'}
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      if (editingUser && onDelete && window.confirm('Are you sure you want to delete this staff member?')) {
                        onDelete(editingUser.id);
                      }
                    }}
                    className="flex-1 py-3 rounded-xl font-bold text-sm flex items-center justify-center gap-2 bg-slate-100 text-slate-500 hover:bg-slate-200"
                  >
                    <Trash2 className="w-4 h-4" /> Delete User
                  </button>
                </div>
              </div>
            )}

            {/* Welcome Message Preview */}
            {formData.username && (
              <div className="space-y-4">
                <h2 className="font-bold text-slate-700">Welcome Message Preview</h2>
                <div className="p-4 bg-gradient-to-r from-amber-50 to-amber-50 rounded-xl border border-amber-100">
                  <p className="text-sm text-amber-700 font-medium">
                    Welcome to clinic dashboard, <span className="font-bold text-amber-900">{formData.username}</span>!
                    We're excited to have you join our team.
                  </p>
                </div>
              </div>
            )}

            {/* Submit Button */}
            <div className="pt-6 border-t border-slate-100">
              <button
                type="submit"
                className="w-full soft-btn-primary py-4 rounded-xl font-bold shadow-amber-200"
              >
                {editingUser ? 'Save Changes' : 'Create Staff Account'}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};
